# Generated by Django 5.2 on 2025-04-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='hosting_plan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='initial_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='lock_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='privacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='domain',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
